# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161129_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_pua',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
