# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20161129_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceindexpage',
            name='body_pua',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
